version: "3.8"
services:
  spotify:
    container_name: spotify
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - ./spotify_manager.db:/app/spotify_manager.db
