services:
  spotify:
    container_name: spotify
    image: spotify-manager
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - spotify_data:/app/data
    environment:
      - DATABASE=/app/data/spotify_manager.db

volumes:
  spotify_data:
